# Generated by Django 6.0.4 on 2026-04-12 00:53

import django.core.validators
import main.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BeachTour',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('direction', models.CharField(choices=[('Istanbul', 'Стамбул'), ('Phuket', 'Пхукет'), ('Dubai', 'Дубай'), ('Zermatt', 'Церматт, Швейцария'), ('Chamonix', 'Шамони, Франция')], max_length=100, verbose_name='Направление')),
                ('departure_date', models.DateField(validators=[main.models.validation_date], verbose_name='Дата выезда')),
                ('duration', models.IntegerField(help_text='дней', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(20)], verbose_name='Продолжительность')),
                ('tour_types', models.CharField(blank=True, choices=[('excursion', 'Экскурсионный'), ('beach', 'Пляжный'), ('ski', 'Горнолыжный')], verbose_name='Дополнительный тур')),
                ('name', models.CharField(max_length=15, verbose_name='Имя')),
                ('surname', models.CharField(max_length=15, verbose_name='Фамилия')),
                ('patronymic', models.CharField(blank=True, max_length=15, verbose_name='Отчество')),
                ('number', models.CharField(max_length=20, verbose_name='Телефон')),
                ('email', models.CharField(max_length=50, verbose_name='Email')),
                ('pasport_series', models.CharField(blank=True, max_length=4, verbose_name='Серия паспорта')),
                ('pasport_number', models.CharField(blank=True, max_length=6, verbose_name='Номер паспорта')),
                ('birth_date', models.DateField(blank=True, null=True, verbose_name='Дата рождения')),
                ('address', models.CharField(blank=True, max_length=100, verbose_name='Место прроживания')),
                ('room_type', models.CharField(blank=True, choices=[('std', 'Стандарт'), ('lux', 'Люкс'), ('suite', 'Апартаменты')], max_length=100, verbose_name='Тип номера')),
                ('breakfast', models.BooleanField(default=False, verbose_name='Завтрак')),
                ('lunch', models.BooleanField(default=False, verbose_name='Обед')),
                ('dinner', models.BooleanField(default=False, verbose_name='Ужин')),
                ('wifi', models.BooleanField(default=False, verbose_name='Wi-Fi')),
                ('med_insurance', models.BooleanField(default=False, verbose_name='Медицинская страховка')),
                ('transport', models.BooleanField(default=False, verbose_name='Транспорт')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ExcursionTour',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('direction', models.CharField(choices=[('Istanbul', 'Стамбул'), ('Phuket', 'Пхукет'), ('Dubai', 'Дубай'), ('Zermatt', 'Церматт, Швейцария'), ('Chamonix', 'Шамони, Франция')], max_length=100, verbose_name='Направление')),
                ('departure_date', models.DateField(validators=[main.models.validation_date], verbose_name='Дата выезда')),
                ('duration', models.IntegerField(help_text='дней', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(20)], verbose_name='Продолжительность')),
                ('tour_types', models.CharField(blank=True, choices=[('excursion', 'Экскурсионный'), ('beach', 'Пляжный'), ('ski', 'Горнолыжный')], verbose_name='Дополнительный тур')),
                ('name', models.CharField(max_length=15, verbose_name='Имя')),
                ('surname', models.CharField(max_length=15, verbose_name='Фамилия')),
                ('patronymic', models.CharField(blank=True, max_length=15, verbose_name='Отчество')),
                ('number', models.CharField(max_length=20, verbose_name='Телефон')),
                ('email', models.CharField(max_length=50, verbose_name='Email')),
                ('pasport_series', models.CharField(blank=True, max_length=4, verbose_name='Серия паспорта')),
                ('pasport_number', models.CharField(blank=True, max_length=6, verbose_name='Номер паспорта')),
                ('birth_date', models.DateField(blank=True, null=True, verbose_name='Дата рождения')),
                ('address', models.CharField(blank=True, max_length=100, verbose_name='Место прроживания')),
                ('programma_tour', models.CharField(blank=True, choices=[('mini', 'Мини-тур (3-4 дня)'), ('classic', 'Классический (7 дней)'), ('extended', 'Расширенный (10-12 дней)')], max_length=100, verbose_name='Программа')),
                ('historical', models.BooleanField(default=False, verbose_name='Исторические достопримечательности')),
                ('museum', models.BooleanField(default=False, verbose_name='Музеи и галереи')),
                ('nature', models.BooleanField(default=False, verbose_name='Природные красоты')),
                ('beach', models.BooleanField(default=False, verbose_name='Пляжный отдых')),
                ('shopping', models.BooleanField(default=False, verbose_name='Шоппинг-туры')),
                ('extreme', models.BooleanField(default=False, verbose_name='Экстремальные развлечения')),
                ('night', models.BooleanField(default=False, verbose_name='Ночная жизнь')),
                ('gastro', models.BooleanField(default=False, verbose_name='Гастрономические туры')),
                ('kids', models.BooleanField(default=False, verbose_name='Семейные программы')),
                ('photo', models.BooleanField(default=False, verbose_name='Фото-туры')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SkiTour',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('direction', models.CharField(choices=[('Istanbul', 'Стамбул'), ('Phuket', 'Пхукет'), ('Dubai', 'Дубай'), ('Zermatt', 'Церматт, Швейцария'), ('Chamonix', 'Шамони, Франция')], max_length=100, verbose_name='Направление')),
                ('departure_date', models.DateField(validators=[main.models.validation_date], verbose_name='Дата выезда')),
                ('duration', models.IntegerField(help_text='дней', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(20)], verbose_name='Продолжительность')),
                ('tour_types', models.CharField(blank=True, choices=[('excursion', 'Экскурсионный'), ('beach', 'Пляжный'), ('ski', 'Горнолыжный')], verbose_name='Дополнительный тур')),
                ('name', models.CharField(max_length=15, verbose_name='Имя')),
                ('surname', models.CharField(max_length=15, verbose_name='Фамилия')),
                ('patronymic', models.CharField(blank=True, max_length=15, verbose_name='Отчество')),
                ('number', models.CharField(max_length=20, verbose_name='Телефон')),
                ('email', models.CharField(max_length=50, verbose_name='Email')),
                ('pasport_series', models.CharField(blank=True, max_length=4, verbose_name='Серия паспорта')),
                ('pasport_number', models.CharField(blank=True, max_length=6, verbose_name='Номер паспорта')),
                ('birth_date', models.DateField(blank=True, null=True, verbose_name='Дата рождения')),
                ('address', models.CharField(blank=True, max_length=100, verbose_name='Место прроживания')),
                ('lifts', models.BooleanField(default=False, verbose_name='Подъемники')),
                ('equipment', models.BooleanField(default=False, verbose_name='Оборудование')),
                ('zermatt_excursion', models.CharField(blank=True, choices=[('matterhorn', 'Маттерхорн')], max_length=20, verbose_name='Горы в Сантьяго')),
                ('chamonix_excursion', models.CharField(blank=True, choices=[('montBlanc', 'Монблан (4 810 м)')], max_length=20, verbose_name='Горы в Шамони')),
                ('programma_tour', models.CharField(blank=True, choices=[('mini', 'Мини-тур (3-4 дня)'), ('classic', 'Классический (7 дней)'), ('extended', 'Расширенный (10-12 дней)')], max_length=100, verbose_name='Программа')),
                ('historical', models.BooleanField(default=False, verbose_name='Исторические достопримечательности')),
                ('museum', models.BooleanField(default=False, verbose_name='Музеи и галереи')),
                ('nature', models.BooleanField(default=False, verbose_name='Природные красоты')),
                ('beach', models.BooleanField(default=False, verbose_name='Пляжный отдых')),
                ('shopping', models.BooleanField(default=False, verbose_name='Шоппинг-туры')),
                ('extreme', models.BooleanField(default=False, verbose_name='Экстремальные развлечения')),
                ('night', models.BooleanField(default=False, verbose_name='Ночная жизнь')),
                ('gastro', models.BooleanField(default=False, verbose_name='Гастрономические туры')),
                ('kids', models.BooleanField(default=False, verbose_name='Семейные программы')),
                ('photo', models.BooleanField(default=False, verbose_name='Фото-туры')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
