# Generated by Django 6.0.4 on 2026-05-05 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_remove_beachtour_address_remove_beachtour_birth_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Presentation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15, verbose_name='Имя')),
                ('surname', models.CharField(max_length=15, verbose_name='Фамилия')),
                ('patronymic', models.CharField(blank=True, max_length=15, verbose_name='Отчество')),
                ('number', models.CharField(max_length=20, verbose_name='Телефон')),
                ('email', models.CharField(max_length=50, verbose_name='Email')),
                ('personal_data', models.BooleanField(default=False, verbose_name='Согласие на обработку персональных данных')),
                ('advertise_valls', models.BooleanField(default=False, verbose_name='Согласие на получение рекламы и звонков')),
            ],
        ),
    ]
