# Generated by Django 6.0.4 on 2026-05-06 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_presentation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='beachtour',
            name='direction',
            field=models.CharField(choices=[('Phuket', 'Пхукет, Таиланд'), ('Hurghada', 'Хургада, Египет'), ('Bali', 'Бали, Индонезия'), ('Male', 'Мале, Мальдивы'), ('Zermatt', 'Церматт, Швейцария'), ('Chamonix', 'Шамони, Франция'), ('Paris', 'Париж, Франция'), ('Rome', 'Рим, Италия'), ('Istambul', 'Стамбул, Турция'), ('Saint-Petersburg', 'Санкт-Петербург, Россия')], max_length=100, verbose_name='Направление'),
        ),
        migrations.AlterField(
            model_name='excursiontour',
            name='direction',
            field=models.CharField(choices=[('Phuket', 'Пхукет, Таиланд'), ('Hurghada', 'Хургада, Египет'), ('Bali', 'Бали, Индонезия'), ('Male', 'Мале, Мальдивы'), ('Zermatt', 'Церматт, Швейцария'), ('Chamonix', 'Шамони, Франция'), ('Paris', 'Париж, Франция'), ('Rome', 'Рим, Италия'), ('Istambul', 'Стамбул, Турция'), ('Saint-Petersburg', 'Санкт-Петербург, Россия')], max_length=100, verbose_name='Направление'),
        ),
        migrations.AlterField(
            model_name='skitour',
            name='direction',
            field=models.CharField(choices=[('Phuket', 'Пхукет, Таиланд'), ('Hurghada', 'Хургада, Египет'), ('Bali', 'Бали, Индонезия'), ('Male', 'Мале, Мальдивы'), ('Zermatt', 'Церматт, Швейцария'), ('Chamonix', 'Шамони, Франция'), ('Paris', 'Париж, Франция'), ('Rome', 'Рим, Италия'), ('Istambul', 'Стамбул, Турция'), ('Saint-Petersburg', 'Санкт-Петербург, Россия')], max_length=100, verbose_name='Направление'),
        ),
    ]
