# Generated by Django 6.0.4 on 2026-05-06 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_beachtour_direction_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='excursiontour',
            name='phuket_excursion',
        ),
        migrations.AddField(
            model_name='excursiontour',
            name='istambul_excursion',
            field=models.CharField(blank=True, choices=[('hagua_sophia', 'Айя-София'), ('blue_mosque', 'Голубая мечеть')], verbose_name='Экскурсия в Стамбул, Турция'),
        ),
        migrations.AddField(
            model_name='excursiontour',
            name='paris_excursion',
            field=models.CharField(blank=True, choices=[('eifell_tower', 'Эйфелева Башня'), ('louvre', 'Лувр'), ('notre_dame', 'Нотр-Даме-де-Пари')], verbose_name='Экскурсия в Париж, Франция'),
        ),
        migrations.AddField(
            model_name='excursiontour',
            name='rome_excursion',
            field=models.CharField(blank=True, choices=[('coliseum', 'Колизей'), ('pantheon', 'Пантеон'), ('st_peter', 'Собр Святого Петра')], verbose_name='Экскурсия в Рим, Италия'),
        ),
        migrations.AddField(
            model_name='excursiontour',
            name='saint_excursion',
            field=models.CharField(choices=[('hermitage', 'Эрмитаж'), ('peter_paul', 'Петропавловская крепость')], default=1, verbose_name='Экскурсия в Санкт-Петербург, Россия'),
            preserve_default=False,
        ),
    ]
