# Generated by Django 6.0.4 on 2026-05-06 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_remove_excursiontour_phuket_excursion_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='excursiontour',
            old_name='istambul_excursion',
            new_name='istanbul_excursion',
        ),
        migrations.AlterField(
            model_name='beachtour',
            name='direction',
            field=models.CharField(choices=[('Phuket', 'Пхукет, Таиланд'), ('Hurghada', 'Хургада, Египет'), ('Bali', 'Бали, Индонезия'), ('Male', 'Мале, Мальдивы'), ('Zermatt', 'Церматт, Швейцария'), ('Chamonix', 'Шамони, Франция'), ('Paris', 'Париж, Франция'), ('Rome', 'Рим, Италия'), ('Istanbul', 'Стамбул, Турция'), ('Saint-Petersburg', 'Санкт-Петербург, Россия')], max_length=100, verbose_name='Направление'),
        ),
        migrations.AlterField(
            model_name='excursiontour',
            name='direction',
            field=models.CharField(choices=[('Phuket', 'Пхукет, Таиланд'), ('Hurghada', 'Хургада, Египет'), ('Bali', 'Бали, Индонезия'), ('Male', 'Мале, Мальдивы'), ('Zermatt', 'Церматт, Швейцария'), ('Chamonix', 'Шамони, Франция'), ('Paris', 'Париж, Франция'), ('Rome', 'Рим, Италия'), ('Istanbul', 'Стамбул, Турция'), ('Saint-Petersburg', 'Санкт-Петербург, Россия')], max_length=100, verbose_name='Направление'),
        ),
        migrations.AlterField(
            model_name='excursiontour',
            name='saint_excursion',
            field=models.CharField(blank=True, choices=[('hermitage', 'Эрмитаж'), ('peter_paul', 'Петропавловская крепость')], verbose_name='Экскурсия в Санкт-Петербург, Россия'),
        ),
        migrations.AlterField(
            model_name='skitour',
            name='direction',
            field=models.CharField(choices=[('Phuket', 'Пхукет, Таиланд'), ('Hurghada', 'Хургада, Египет'), ('Bali', 'Бали, Индонезия'), ('Male', 'Мале, Мальдивы'), ('Zermatt', 'Церматт, Швейцария'), ('Chamonix', 'Шамони, Франция'), ('Paris', 'Париж, Франция'), ('Rome', 'Рим, Италия'), ('Istanbul', 'Стамбул, Турция'), ('Saint-Petersburg', 'Санкт-Петербург, Россия')], max_length=100, verbose_name='Направление'),
        ),
    ]
