# Generated by Django 6.0.4 on 2026-05-07 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_rename_istambul_excursion_excursiontour_istanbul_excursion_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='skitour',
            old_name='chamonix_excursion',
            new_name='chamonix_ski',
        ),
        migrations.RenameField(
            model_name='skitour',
            old_name='zermatt_excursion',
            new_name='zermatt_ski',
        ),
        migrations.AlterField(
            model_name='beachtour',
            name='direction',
            field=models.CharField(choices=[('Phuket', 'Пхукет, Таиланд'), ('Hurghada', 'Хургада, Египет'), ('Bali', 'Бали, Индонезия'), ('Male', 'Мале, Мальдивы'), ('Zermatt', 'Церматт, Швейцария'), ('Grindelwald', 'Гриндельвальд, Швейцария'), ('Chamonix', 'Шамони, Франция'), ('Caruiso', 'Каруизо, Италия'), ('Paris', 'Париж, Франция'), ('Rome', 'Рим, Италия'), ('Istanbul', 'Стамбул, Турция'), ('Saint-Petersburg', 'Санкт-Петербург, Россия')], max_length=100, verbose_name='Направление'),
        ),
        migrations.AlterField(
            model_name='excursiontour',
            name='direction',
            field=models.CharField(choices=[('Phuket', 'Пхукет, Таиланд'), ('Hurghada', 'Хургада, Египет'), ('Bali', 'Бали, Индонезия'), ('Male', 'Мале, Мальдивы'), ('Zermatt', 'Церматт, Швейцария'), ('Grindelwald', 'Гриндельвальд, Швейцария'), ('Chamonix', 'Шамони, Франция'), ('Caruiso', 'Каруизо, Италия'), ('Paris', 'Париж, Франция'), ('Rome', 'Рим, Италия'), ('Istanbul', 'Стамбул, Турция'), ('Saint-Petersburg', 'Санкт-Петербург, Россия')], max_length=100, verbose_name='Направление'),
        ),
        migrations.AlterField(
            model_name='skitour',
            name='direction',
            field=models.CharField(choices=[('Phuket', 'Пхукет, Таиланд'), ('Hurghada', 'Хургада, Египет'), ('Bali', 'Бали, Индонезия'), ('Male', 'Мале, Мальдивы'), ('Zermatt', 'Церматт, Швейцария'), ('Grindelwald', 'Гриндельвальд, Швейцария'), ('Chamonix', 'Шамони, Франция'), ('Caruiso', 'Каруизо, Италия'), ('Paris', 'Париж, Франция'), ('Rome', 'Рим, Италия'), ('Istanbul', 'Стамбул, Турция'), ('Saint-Petersburg', 'Санкт-Петербург, Россия')], max_length=100, verbose_name='Направление'),
        ),
    ]
