# Generated by Django 6.0.4 on 2026-05-08 12:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_rename_chamonix_excursion_skitour_chamonix_ski_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='beachtour',
            old_name='bali_excursion',
            new_name='bali_beach',
        ),
        migrations.RenameField(
            model_name='beachtour',
            old_name='hurghada_excursion',
            new_name='hurghada_beach',
        ),
        migrations.RenameField(
            model_name='beachtour',
            old_name='male_excursion',
            new_name='male_beach',
        ),
        migrations.RenameField(
            model_name='beachtour',
            old_name='phuket_excursion',
            new_name='phuket_beach',
        ),
    ]
