# Generated by Django 6.0.4 on 2026-05-08 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_rename_bali_excursion_beachtour_bali_beach_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='skitour',
            name='equipment',
        ),
        migrations.RemoveField(
            model_name='skitour',
            name='lifts',
        ),
        migrations.AddField(
            model_name='skitour',
            name='caruiso_ski',
            field=models.CharField(blank=True, choices=[('Val-Gardena', 'Валь-Гардена'), ('Gran San Bernardo', 'Гран-Сан-Бернардо')], verbose_name='Гора в Валь-Гардена, Гран-Сан-Бернардо, Италия'),
        ),
        migrations.AddField(
            model_name='skitour',
            name='grindelwald_ski',
            field=models.CharField(blank=True, choices=[('iger', 'Айгер')], verbose_name='Гора в Гриндельвальд, Швейцария'),
        ),
    ]
