# Generated by Django 6.0.4 on 2026-05-11 09:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_remove_skitour_equipment_remove_skitour_lifts_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='excursiontour',
            name='status',
            field=models.CharField(choices=[('pending', 'Новая'), ('processing', 'В обработке'), ('completed', 'Завершено')], default='pending'),
        ),
        migrations.AddField(
            model_name='excursiontour',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
