# Generated by Django 6.0.4 on 2026-05-14 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_beachtour_user_skitour_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='beachtour',
            name='status',
            field=models.CharField(choices=[('pending', 'Новая'), ('processing', 'В обработке'), ('completed', 'Завершено')], default='pending'),
        ),
        migrations.AddField(
            model_name='skitour',
            name='status',
            field=models.CharField(choices=[('pending', 'Новая'), ('processing', 'В обработке'), ('completed', 'Завершено')], default='pending'),
        ),
    ]
