# Generated by Django 6.0.4 on 2026-05-14 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_beachtour_status_skitour_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='beachtour',
            name='status',
            field=models.CharField(choices=[('pending', 'Новая'), ('processing', 'В обработке'), ('cancel', 'Отменено'), ('completed', 'Завершено')], default='pending'),
        ),
        migrations.AlterField(
            model_name='excursiontour',
            name='status',
            field=models.CharField(choices=[('pending', 'Новая'), ('processing', 'В обработке'), ('cancel', 'Отменено'), ('completed', 'Завершено')], default='pending'),
        ),
        migrations.AlterField(
            model_name='skitour',
            name='status',
            field=models.CharField(choices=[('pending', 'Новая'), ('processing', 'В обработке'), ('cancel', 'Отменено'), ('completed', 'Завершено')], default='pending'),
        ),
    ]
