# Generated by Django 6.0.4 on 2026-06-13 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_alter_beachtour_status_alter_excursiontour_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='beachtour',
            name='status',
            field=models.CharField(choices=[('pending', 'НОВАЯ'), ('processing', 'В ОБРАБОТКЕ'), ('completed', 'ЗАВЕРШЕНО'), ('cancel', 'ОТМЕНЕНО')], default='pending'),
        ),
        migrations.AlterField(
            model_name='excursiontour',
            name='rome_excursion',
            field=models.CharField(blank=True, choices=[('coliseum', 'Колизей'), ('pantheon', 'Пантеон'), ('st_peter', 'Собр Св. Петра')], verbose_name='Экскурсия в Рим, Италия'),
        ),
        migrations.AlterField(
            model_name='excursiontour',
            name='saint_excursion',
            field=models.CharField(blank=True, choices=[('hermitage', 'Эрмитаж'), ('peter_paul', 'Петропавл. крепость')], verbose_name='Экскурсия в Санкт-Петербург, Россия'),
        ),
        migrations.AlterField(
            model_name='excursiontour',
            name='status',
            field=models.CharField(choices=[('pending', 'НОВАЯ'), ('processing', 'В ОБРАБОТКЕ'), ('completed', 'ЗАВЕРШЕНО'), ('cancel', 'ОТМЕНЕНО')], default='pending'),
        ),
        migrations.AlterField(
            model_name='skitour',
            name='caruiso_ski',
            field=models.CharField(blank=True, choices=[('ValGardena', 'Валь-Гардена'), ('GranSanBernardo', 'Гран-Сан-Бернардо')], verbose_name='Гора в Валь-Гардена, Гран-Сан-Бернардо, Италия'),
        ),
        migrations.AlterField(
            model_name='skitour',
            name='status',
            field=models.CharField(choices=[('pending', 'НОВАЯ'), ('processing', 'В ОБРАБОТКЕ'), ('completed', 'ЗАВЕРШЕНО'), ('cancel', 'ОТМЕНЕНО')], default='pending'),
        ),
    ]
